FuneralApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/',views.SignUp, name='signup'),
    path('register/<int:pk>/',views.register, name='register'),
    path('',views.home, name='home'),
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout,name='logout'),
    path('create_memorial/',views.create_memorial,name='create_memorial'),
    path('create_biography/<int:pk>/',views.create_biography, name='create_biography'),
    path('memorials/',views.DeceasedList,name='memorials'),

    #path('create-photo/<int:pk>/',views.create_photo, name='create-photo'),
    path('create-photo/<int:pk>/',views.create_photo, name='create-photo'),
    path('delete-photo/<int:formset_id>/', views.delete_photo, name='delete-photo'),

    path('create-facts/<int:pk>/',views.create_facts, name='create-facts'),
    path('delete-facts/<int:formset_id>/', views.delete_facts, name='delete-facts'),

    path('add-comment/<int:photoId>/', views.add_comment, name='add_comment'),
    path('photos/<int:photo_id>/comments/',views.photo_comments, name='photo_comments'),
    path('delete-comment/<int:commentId>/', views.delete_comment, name='delete_comment'),

    path('invite-contributor/', views.invite_contributor, name='invite_contributor'),
    path('register_contributor/', views.register_contributor, name='register_contributor'),

    path('like-photo/<int:photoId>/', views.like_photo, name='like_photo'),
    path('like-list/<int:photoId>/', views.like_list, name='like_list'),
    path('like-cover/<int:photoId>/', views.like_cover, name='like_cover'),
    path('cover-like-list/<int:photoId>/', views.cover_like_list, name='cover_like_list'),

    path('create-event/',views.create_event,name= 'create-event'),
    path('edit-event/<int:pk>/',views.edit_event,name= 'edit-event'),
    path('account/<int:pk>/',views.account, name = 'account'),
    path('delete-event/<int:eventId>/', views.delete_event, name='delete-event'),
    path('recent-memorial/',views.recent_memorial,name='recent_memorial'),

    path('search-memorials/',views.search_memorials,name='search_memorials'),


    path('add-tribute/<int:deceasedId>/', views.add_tribute, name='add-tribute'),
    path('tribute/<int:deceasedId>/list/',views.list_tribute, name='list-tribute'),
    path('delete-tribute/<int:commentId>/', views.delete_tribute, name='delete_tribute'),
]

FuneralSite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from allauth.account.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',include('FuneralApp.urls')),
    path('accounts/', include('allauth.urls')),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

"""
 path('accounts/', include('allauth.urls')),
        path('accounts/login/', SignupView.as_view(
            template_name='FuneralApp/signup.html',
            extra_context={'provider': 'google'}
    ), name='google_signup'),"""

FuneralApp/models.py
from django.db import models
#from ckeditor_uploader.fields import RichTextUploadingField
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.conf import settings
#from django_countries.fields import CountryField

#from .fields import OrderField
from .manager import CustomUserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

'''deceased>>memorial>>biography'''


class myuser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=40,blank=False)
    last_name = models.CharField(max_length=40,blank=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)



    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name',]
    objects = CustomUserManager()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'







class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Profile/',blank=True,null=True)
    address = models.CharField(max_length=100,blank=True,null=True)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='following',blank=True,null=True)
    phone_number = models.CharField(max_length=11,blank=True,null=True)

    def __str__(self):
        return f'{self.user.first_name}'




month_choices = [
    ('January','January'),
    ('February','February'),
    ('March','March'),
    ('April','April'),
    ('May',',May'),
    ('June','June'),
    ('July','July'),
    ('August','August'),
    ('September','September'),
    ('October','October'),
    ('November','November'),
    ('December','December'),
]

from django.core.validators import MinValueValidator

class Deceased(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null =True,blank = True)
    #contributors = models.ManyToManyField(Contributor, blank=True,null=True)
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255,blank=True,null=True)
    last_name = models.CharField(max_length=255)
    death_cause = models.CharField(max_length=255,blank=True,null=True)
    month_birth = models.CharField(max_length=100,choices=month_choices)
    day_birth = models.IntegerField()
    year_birth = models.IntegerField(blank=True,null=True)

    #year_birth = models.IntegerField(
        #validators=[MinValueValidator(1901)],
        #error_messages={'invalid': ('Year must be greater than or equal to 1901',)}
    #)

    month_death = models.CharField(max_length=100,choices=month_choices,blank=True,null=True)
    day_death= models.IntegerField(blank=True,null=True)
    year_death = models.IntegerField(blank=True,null=True)
    location = models.CharField(max_length=100,blank=True,null=True)



    def __str__(self):
        return self.first_name


class Contributor(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    invitation_token = models.CharField(max_length=100, unique=True)
    invited_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contributor_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='contributors_user',blank=True,null=True)
    memorials = models.ForeignKey(Deceased,on_delete=models.CASCADE, related_name='contributors',null=True,blank=True)



facts_choices = [
    ('1','Place of birth'),
    ('2','Most recently lived in'),
    ('3','favorite hobbies'),
    ('4','favorite foods'),
    ('5','Favorite bands and musical artists'),
    ('6','Interesting facts about'),
    ('7','If you could tell anything today, what would you say?'),
    ('8','loved nothing more than'),
    ('9','Favorite place in the world'),
    ('10','Favorite sports'),
    ('11','Favorite movies'),
    ('12',"profession(s)"),
    ('13',"superpower"),
    ('14',"proudest accomplishments"),
    ('15',"pets in life"),
    ('17',"Favorite ice cream flavor"),
    ('18',"Places traveled to"),

    ('19',"Name of High School attended"),
    ('20',"Name of college attended"),
    ('21',"Name of  parents"),
    ('22',"Name of siblings"),
    ('23',"Name of children"),
    ('24',"Name of grandchildren"),
]


ceremony = [
    ('1','Funeral'),
    ('2','Graveside Service'),
    ('3','Viewing Service'),
    ('4','Visitation Service'),
    ('5','Memorial Service'),
    ('6','Celebration of Life'),
    ('7','Wake'),
    ('8','Other'),
]
class Event(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    deceased = models.ForeignKey(Deceased,on_delete=models.CASCADE)
    celebration_type = models.CharField(max_length=100,choices=ceremony)
    description = models.TextField()
    date = models.DateTimeField()
    location = models.CharField(max_length=100)
    streaming_link = models.CharField(max_length=100,blank=True,null=True)
    host_image = models.ImageField(upload_to='host-image/',blank=True,null=True)

    def __str__(self):
        return f'{self.celebration_type}'

    class Meta:
        ordering = ['-id']


class BiographyFacts(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    deceased = models.ForeignKey(Deceased,on_delete=models.CASCADE)
    #biography = models.TextField(blank=True,null=True)
    facts = models.CharField(max_length=100,choices=facts_choices,blank=True,null=True)
    description = models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return self.facts

    class Meta:
        ordering = ('id',)



class PhotoAlbum(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    deceased = models.ForeignKey(Deceased,on_delete=models.CASCADE)
    title = models.CharField(max_length=100,null=True,blank=True)
    date = models.DateField(blank=True,null=True)
    image = models.FileField(upload_to='Albums/',null=True,blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_photos', blank=True)

    def __str__(self):
        return self.title




from ckeditor.fields import RichTextField

class Biography(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    deceased = models.ForeignKey(Deceased,on_delete=models.CASCADE,related_name='biography')
    body_text = RichTextField(null=True, blank=True)
    #new
    introduction = models.TextField(blank =True,null=True)
    early_life = models.TextField(blank =True,null=True)
    career = models.TextField(blank =True,null=True)
    personal_life = models.TextField(blank =True,null=True)
    Awards = models.TextField(blank =True,null=True)

    cover_photo = models.ImageField(null=True, blank=True,upload_to = 'CoverPhoto/')
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_cover', blank=True)

    def __str__(self):
        return self.deceased.first_name

    class Meta:
        ordering = ['-id']



from django.utils import timezone
class Comments(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ForeignKey(PhotoAlbum,on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_comment', blank=True)
    heart = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='heart_comment', blank=True)

    def get_time_since_comment(self):
        time_difference = timezone.now() - self.date

        if time_difference.total_seconds() < 60:  # Less than a minute
            return f"{int(time_difference.total_seconds())} sec ago"
        elif time_difference.total_seconds() < 3600:  # Less than an hour
            minutes = int(time_difference.total_seconds() / 60)
            return f"{minutes} mins ago"
        elif time_difference.total_seconds() < 86400:  # Less than a day
            hours = int(time_difference.total_seconds() / 3600)
            return f"{hours} hours ago"
        elif time_difference.total_seconds() < 604800:  # Less than a week
            days = int(time_difference.total_seconds() / 86400)
            return f"{days} days ago"
        elif time_difference.total_seconds() < 2592000:  # Less than a month
            weeks = int(time_difference.total_seconds() / 604800)
            return f"{weeks} weeks ago"
        elif time_difference.total_seconds() < 31536000:  # Less than a year
            months = int(time_difference.total_seconds() / 2592000)
            return f"{months} months ago"
        else:
            years = int(time_difference.total_seconds() / 31536000)
            return f"{years} years ago"



class Tribute(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    deceased = models.ForeignKey(Deceased,on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_tribute', blank=True)
    heart = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='heart_tribute', blank=True)

    def get_time_since_comment(self):
        time_difference = timezone.now() - self.date

        if time_difference.total_seconds() < 60:  # Less than a minute
            return f"{int(time_difference.total_seconds())} sec ago"
        elif time_difference.total_seconds() < 3600:  # Less than an hour
            minutes = int(time_difference.total_seconds() / 60)
            return f"{minutes} mins ago"
        elif time_difference.total_seconds() < 86400:  # Less than a day
            hours = int(time_difference.total_seconds() / 3600)

FuneralApp/templates/FuneralApp/bottom-wrapper.html
<div class="wrapper">
                            <div class="header">
                                <div class="in">In memory of </div>
                                <div class="name">{{deceased.first_name}} {{deceased.last_name}}</div>
                                <div class="month-deceased">{{deceased.month_birth}} {{deceased.year_birth}} - {{deceased.month_death}} {{deceased.year_death}}</div>
                                {% if parent.cover_photo %}
                                <img class="mem-img" src="{{parent.cover_photo.url}}" alt="">
                                {% endif %}
                               <!--  <div class="family-card">
                                    <div class="title">Family & Friends</div>
                                    <div class="family-wrapper">
                                        {% for item in  relationship %}
                                        <div class="image-box">
                                           <a href="{% url 'profile' item.user.id item.user.first_name %}">
                                            {% if item.user.profile.image %}
                                            <img class="f-image" src="{{item.user.profile.image.url}}" alt="">
                                            {% else %}
                                            <img class="f-image" src="{% static 'images/default.png' %}" alt="">
                                            {% endif %}

                                           </a>
                                            <div class="f-name">{{item.user.first_name}} {{item.user.last_name}}</div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>-->
                                <div class="what">What can you do?</div>
                            </div>
                            <div class="items">
                                 {% if event_list %}
                                <!--<div class="title">Upcoming Event</div>-->

                                {% for data in event_list %}
                                {% if data.host_image %}
                                <div class="event-img">
                                    <img class="mem-img" src="{{data.host_image.url}}" alt="">
                                </div>
                                {% endif %}
                                <div class="text">HOST:{{data.user}}</div>
                                <div class="text">Ceremony:{{data.get_celebration_type_display}}</div>
                                <div class="text">Date:{{data.date}}</div>
                                <div class="text">streaming link:{{data.streaming_link}}</div>
                                <div class="text" style="margin-bottom: 30px;">Location:{{data.location}}</div>
                                {% endfor %}

                                {% endif %}
                            </div>
                            <div class="items">
                                <!--<div class="title">Add Photos</div>-->
                                 <div class="link-wrapper">
                                    <a href="{% url 'create-photo' deceased.id %}" class="links">
                                        <div class="icons"><i class="fa-regular fa-square-plus"></i></div>
                                        <div class="text">Add Photos</div>
                                    </a>
                                </div>
                                <div class="text" id = 'more-photo'>Contribute with your photos, videos or stories to {{deceased.first_name}} {{deceased.last_name}}'s Memorial to help {{deceased.first_name}}'s family and friends come back to more memories.</div>
                                <button onclick="myFunction2()" id="myBtn-photo" class="read-btn">
                                    <i class="fa-solid fa-circle-plus"></i> <span class="text">Read more</span>
                                </button>
                            </div>
                            <div class="items">
                               <!-- <div class="title">Support</div>-->
                                <div class="link-wrapper">
                                    <a href="" class="links">
                                        <div class="icons"><i class="fa-regular fa-square-plus"></i></div>
                                        <div class="text">Light a candle</div>
                                    </a>
                                </div>

                                <div class="text" id = 'more-photo3'>Light a candle to show your support for {{deceased.first_name}} {{deceased.last_name}} and ensure their memory lives on forever. Your contribution helps to keep our website free for all grieving families.</div>
                                  <button onclick="myFunction3()" id="myBtn-photo3" class="read-btn">
                                    <i class="fa-solid fa-circle-plus"></i> <span class="text">Read more</span>
                                </button>

                            </div>


                            <div class="items">
                                <div class="title">Share</div>
                                <div class="clip-board">
                                    <div class="texts" id="copy-text-m" style="font-size: 0.8rem;overflow-x: hidden;text-overflow: ellipsis;">https://futurismx.pythonanywhere.com/create_biography/{{deceased.id}}/</div>
                                    <div class="icon" id="clip-board-m" >
                                        <i class="fa-regular fa-square-plus">
                                        <div id="copied-m">Copied!</div>
                                    </i></div>

                                </div>

                                <div class="share-tray">
                                    <div class="box" onclick="share_whatsapp(fname = '{{deceased.first_name}}',lname = '{{deceased.last_name}}',month = '{{deceased.month_death}}',year = '{{deceased.year_death}}',url='https://futurismx.pythonanywhere.com/create_biography/{{deceased.id}}')">
                                        <div class="icon"><i class="fa-brands fa-whatsapp"></i></div>

                                    </div>
                                    <div class="box" onclick="share_twitter(fname = '{{deceased.first_name}}',lname = '{{deceased.last_name}}',month = '{{deceased.month_death}}',year = '{{deceased.year_death}}',url='https://futurismx.pythonanywhere.com/create_biography/{{deceased.id}}' )">
                                        <div class="icon"><i class="fa-brands fa-twitter"></i></div>

                                    </div>
                                    <div class="box" onclick="share_messenger(fname = '{{deceased.first_name}}',lname = '{{deceased.last_name}}',month = '{{deceased.month_death}}',year = '{{deceased.year_death}}',url='https://futurismx.pythonanywhere.com/create_biography/{{deceased.id}}')">
                                        <div class="icon" ><i class="fa-brands fa-facebook-messenger"></i></div>

                                    </div>
                                    <div class="box" onclick="share_facebook(fname = '{{deceased.first_name}}',lname = '{{deceased.last_name}}',month = '{{deceased.month_death}}',year = '{{deceased.year_death}}',url='https://futurismx.pythonanywhere.com/create_biography/{{deceased.id}}')">
                                        <div class="icon"><i class="fa-brands fa-square-facebook"></i></div>

                                    </div>

                                </div>
                            </div>
                        </div>

FuneralApp/templates/FuneralApp/candle.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap" rel="stylesheet">
    <title>EXIIT</title>
</head>
<style>

body{
	background:#000;
}
.holder {
  margin: 12rem auto 0;
  width: 150px;
  height: 200px;
  position: relative;
}
.holder *, .holder *:before, .holder *:after {
  position: absolute;
  content: "";
}

.candle {
  bottom: 0;
  width: 150px;
  height: 200px;
  border-radius: 150px / 40px;

  background: #190f02;
 background: linear-gradient(#e48825, #e78e0e, #833c03);
}
.candle:before {
  width: 100%;
  height: 40px;
  border-radius: 50%;
  border: 1px solid #d47401;
  background: #b86409;

}

.candle:after {
  width: 33px;
  height: 10px;
  left: 50%;
  transform: translateX(-50%);
  border-radius: 50%;
  top: 14px;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);

}

.thread {
  width: 6px;
  height: 36px;
  top: -17px;
  left: 50%;
  z-index: 1;
  border-radius: 40% 40% 0 0;
  transform: translateX(-50%);
  background: #121212;

}

.flame {
  width: 24px;
  height: 120px;
  left: 50%;
  transform-origin: 50% 100%;
  transform: translateX(-50%);
  bottom: 100%;
  border-radius: 50% 50% 20% 20%;


  background: linear-gradient(white 80%, transparent);
  animation: moveFlame 4s linear infinite, enlargeFlame 3s linear infinite;
}

@keyframes moveFlame {
  0%, 100% {
    transform: translateX(-50%) rotate(-5deg);
  }
  50% {
    transform: translateX(-50%) rotate(5deg);
  }
}

@keyframes enlargeFlame {
  0%, 100% {
    height: 120px;
  }
  50% {
    height: 140px;
  }
}

.glow {
  width: 26px;
  height: 60px;
  border-radius: 50% 50% 35% 35%;
  left: 50%;
  top: -48px;
  transform: translateX(-50%);
  background: rgba(0, 133, 255, .7);
  box-shadow: 0 -40px 30px 0 #dc8a0c, 0 40px 50px 0 #dc8a0c,
  inset 3px 0 2px 0 rgba(0, 133, 255, .6),
  inset -3px 0 2px 0 rgba(0, 133, 255, .6);
}

.glow:before {
  width: 70%;
  height: 60%;
  left: 50%;
  transform: translateX(-50%);
  bottom: 0;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.35);
}

.blinking-glow {
  width: 100px;
  height: 180px;
  left: 50%;
  top: -55%;
  transform: translateX(-50%);
  border-radius: 50%;
  background: #ff6000;

  filter: blur(60px);
  animation: blinkIt .1s infinite;
}

@keyframes blinkIt {
  50% { opacity: .8;}
}


h1{
  font-family: 'Fugaz One', cursive;
}
</style>
<body>
    <div class="holder">

        <div class="candle">
            <div class="blinking-glow"></div>
            <div class="thread"></div>
            <div class="glow"></div>
            <div class="flame"></div>
        </div>
    </div>

  <div style="text-align: center;">
    <h1 style="color: white;text-align: center;" >in loving memory of {{deceased.first_name}} {{deceased.last_name}}</h1>
    <audio hidden id="myAudio" controls autoplay loop src="{% static 'images/too.mp3' %}" ></audio>
  </div>
</body>
<script>
  var audio = document.getElementById("myAudio");
  audio.play();
</script>
</html>

FuneralApp/templates/FuneralApp/edit-event.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create-Photos</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/edit-event.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Unna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<style>
    
</style>
<body >
    {% if messages %}
    {% for message in messages %}
    <div id="messages">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <div class="photo-container">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="header">
                <div class="title">{{deceased.first_name}}'s {{event.get_celebration_type_display}}</div>
                <a href="" class="btn-x" ><i class="fa-solid fa-xmark"></i></a>
            </div>
            <div class="photo-wrapper">
                <div class="container-a">
                    <h1 class="meaning">{{event.get_celebration_type_display}}</h1>

                    {% if EventForm.non_form_errors %}
                    <div class="alert alert-danger">
                        {% for error in EventForm.non_form_errors %}
                            <h1>{{ error }}</h1>
                        {% endfor %}
                    </div>
                    {% endif %}
                
                    {% for form in EventForm %}
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            {% for error in form.errors %}
                                {{ error }}
                                <h1>{{form.errors}}</h1>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <!-- display the form fields here -->
                    {% endfor %}
                    <div id="book-formset">
                        <div  class="event-container" >
                            <div class="title">Edit Event</div>  
                            <input type="hidden" name="deceased" value="{{deceased.id}}">
                            <input type="hidden" name="user" value="{{request.user.id}}">
                           
                            <div class="event-card">
                                <div class="label">Ceremony type</div>
                                {{EventForm.celebration_type}}
                            </div>
                           
                            <div class="event-card">
                                <div class="label">Description</div>
                                <!--<textarea name="" id="" cols="30" rows="5" autofocus></textarea>-->
                                {{EventForm.description}}
                            </div>
                        
                            <div class="event-card">
                                <div class="label">
                                    <i class="fa-regular fa-calendar-days"></i>
                                    Start date & time
                                </div>
                                {{EventForm.date}}
                            </div>
                            <div class="event-card">
                                <div class="label">
                                    <i class="fa-solid fa-location-dot"></i>
                                    Location
                                </div>
                                {{EventForm.location}}
                           
                            </div>
                        
                            <div class="event-card">
                                <div class="label">
                                    <i class="fa-solid fa-video"></i>
                                    Streaming Link(Optional)
                                </div>
                                {{EventForm.streaming_link}}
                            </div>
                        
                           
                            
                        </div>
                       
                    </div>



                 
                    
                </div>
            </div>
    
            <div class="footer" >
                <button type="submit">Save</button>
            </div>
        </form>
    </div>
   
</body>
<script src="{% static 'javascript/edit-event.js' %}"></script>
</html>

FuneralApp/templates/FuneralApp/family.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap" rel="stylesheet">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/family.css' %}">
</head>
<body>
    {% if messages %}
    {% for message in messages %}
    <div id="messages">{{ message }}</div>
    {% endfor %}
    {% endif %}

    <div class="family-container">
      
        <form action="" method="post">
            {% csrf_token %}
            <div class="header">
                <h1 class="title">Add family and friends</h1>
                <p>Family is not defined by our genes, but by the people in our lives who love us and support us</p>
            </div>

            <div class="input-container">
                <select name="deceased" required="" id="id_deceased" hidden>
                    <option selected value="{{deceased.id}}">{{deceased.first_name}}}</option>
                </select>
               <div class="items">
                    <label for="">User</label>
                    <input  id="search-bar" type="text" placeholder="Search for users...">
                    <input type="hidden" id="user" name="user" required>
               </div>

               <div class="items">
                    <label for="">Relationship</label>
                   {{form.relationship_type }}
                </div>
            </div>

            <div class="btn-card">
                <button type="submit">Add to friends & family</button>
            </div>
        </form>
    </div>
</body>

<script src="{% static 'javascript/family.js' %}"></script>
</html>

FuneralApp/templates/FuneralApp/old_bio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>